chess: main.cpp Chess.cpp Board.cpp Pawn.cpp Rook.cpp Bishop.cpp Knight.cpp Queen.cpp King.cpp Utils.cpp CreatePiece.cpp
	g++ -o chess main.cpp Chess.cpp Board.cpp Pawn.cpp Rook.cpp Bishop.cpp Knight.cpp Queen.cpp King.cpp Utils.cpp CreatePiece.cpp Mystery.h -Wall -Wextra -std=c++11 -pedantic
